
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author 64273
 */
public class SignInForm extends javax.swing.JFrame {

    UserRepository ur = new UserRepository();
    StartGameForm st = new StartGameForm();
    ScoreRepository sr = new ScoreRepository();

    /**
     * Creates new form SignInForm
     */
    public SignInForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel_SignIn_Username = new javax.swing.JLabel();
        jLabel_SignIn_Password = new javax.swing.JLabel();
        jTextField_LogIn_Username = new javax.swing.JTextField();
        jPasswordField_LogIn_Password = new javax.swing.JPasswordField();
        jButton_LogIn_SignIn = new javax.swing.JButton();
        jLabel_LogIn_CreateAccout = new javax.swing.JLabel();
        jButton_LogIn_BackToFirstPage = new javax.swing.JButton();

        jButton3.setText("Back to First Page");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jTextField1.setText("LOG IN");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel_SignIn_Username.setText("Username");

        jLabel_SignIn_Password.setText("Password");

        jPasswordField_LogIn_Password.setText("jPasswordField1");

        jButton_LogIn_SignIn.setText("SIGN IN");
        jButton_LogIn_SignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_LogIn_SignInMouseClicked(evt);
            }
        });
        jButton_LogIn_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogIn_SignInActionPerformed(evt);
            }
        });

        jLabel_LogIn_CreateAccout.setText("Haven't got an account? Sign up");
        jLabel_LogIn_CreateAccout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LogIn_CreateAccoutMouseClicked(evt);
            }
        });

        jButton_LogIn_BackToFirstPage.setText("Back to First Page");
        jButton_LogIn_BackToFirstPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_LogIn_BackToFirstPageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_SignIn_Password)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordField_LogIn_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel_LogIn_CreateAccout, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_SignIn_Username)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_LogIn_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_LogIn_SignIn)
                        .addGap(151, 151, 151))
                    .addComponent(jButton_LogIn_BackToFirstPage, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SignIn_Username)
                    .addComponent(jTextField_LogIn_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SignIn_Password)
                    .addComponent(jPasswordField_LogIn_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButton_LogIn_SignIn)
                .addGap(18, 18, 18)
                .addComponent(jLabel_LogIn_CreateAccout, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton_LogIn_BackToFirstPage))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton_LogIn_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogIn_SignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_LogIn_SignInActionPerformed

    private void jLabel_LogIn_CreateAccoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LogIn_CreateAccoutMouseClicked
        // Go to Sign Up form
        SignUpForm su = new SignUpForm();
        su.setVisible(true);
        su.pack();
        su.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_LogIn_CreateAccoutMouseClicked

    private void jButton_LogIn_SignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LogIn_SignInMouseClicked
        // Get input value
        String inputUsername = jTextField_LogIn_Username.getText();
        String inputPassword = String.valueOf(jPasswordField_LogIn_Password.getPassword());

        // Check empty fields
        boolean emptyFields = inputUsername.trim().equals("") || inputPassword.trim().equals("");

        if (!emptyFields) {
            // check inputUsername and inputPassword match with the database
            boolean match = ur.checkUsernamePasswordMatch(inputUsername, inputPassword);

            if (match) {
                //Get all user info
                String firstName = "";
                String lastName = "";
                String username = "";
                String password = "";
                int highestScore = sr.getUserHighestScore(inputUsername);
                ResultSet rs = ur.getUserFromUsername(inputUsername);
                try {
                    if (rs.next()) {
                        firstName = rs.getString("username");
                        lastName = rs.getString("lastname");
                        username = rs.getString("username");
                        password = rs.getString("password");                                
                    }
                } catch (SQLException e) {
                    System.out.println(e);
                }
                
                // Implement method to set all field in StartGame form
                st.innitialiseStartGameForm(firstName, lastName, username, password, highestScore);
                // Go to StartGame form
                st.setVisible(true);
                st.pack();
                st.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();

                st.setVisible(true);
                st.pack();
                st.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Username and/or password are/is incorrect! Please input again",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            //If there is empty fields: Show message, input again
            JOptionPane.showMessageDialog(this, "You must input all fields",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_LogIn_SignInMouseClicked

    private void jButton_LogIn_BackToFirstPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LogIn_BackToFirstPageMouseClicked
        // Go to FirstPage form
        FirstPageForm fp = new FirstPageForm();
        fp.setVisible(true);
        fp.pack();
        fp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_LogIn_BackToFirstPageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_LogIn_BackToFirstPage;
    private javax.swing.JButton jButton_LogIn_SignIn;
    private javax.swing.JLabel jLabel_LogIn_CreateAccout;
    private javax.swing.JLabel jLabel_SignIn_Password;
    private javax.swing.JLabel jLabel_SignIn_Username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_LogIn_Password;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_LogIn_Username;
    // End of variables declaration//GEN-END:variables
}
